pipeline {
    agent any

    environment {
        DOCKER_IMAGE = 'ankushadda247/todo-app'  // Change this
    }

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/Ankush247-devops/todo-app.git'  // Change this
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t $DOCKER_IMAGE .'
                }
            }
        }

        stage('Login to Docker Hub') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: '207ca5eb-f0ad-47de-b9d3-60aee4d3a53a', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                        sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    sh 'docker push $DOCKER_IMAGE'
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    echo "Deploying to Kubernetes (Minikube or any cluster)..."
                    // You can add `kubectl apply -f deployment.yaml` here if needed
                }
            }
        }
    }
}
